language: python

python:
  - "3.5"
  - "3.6"

sudo: false

services:
  - mysql

install:
  - pip install coveralls
  - pip install cryptography

before_script:
  - mysql -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'";
  - mysql -e 'create database testhat;'
  - cp tests/tests.conf.sample tests/tests.conf

script:
  - coverage run --source=sortinghat setup.py test

after_success:
  - coveralls

notifications:
  irc: "chat.freenode.net#grimoirelab"

branches:
  except:
  - muggle

